language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
# command to run tests, e.g. python setup.py test
install: pip install virtualenv
script: 
  - make env
  - .env/bin/python scripts/test_and_pylint.py
after_success:
  coveralls
